version: 2.1

jobs:

  test:
    working_directory: /bender/zpy
    environment:
      SIM_ID: 038694c1-f4f7-492f-94e6-d09904061567
      ASSETS: /tmp
    docker:
      - image: zumolabs/bender:latest
        auth:
          username: nponte
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run:
          name: fetch sim
          command: |
            apt-get update
            apt-get install -qy awscli

            aws s3 cp s3://zumo-labs/prod/ragnarok-sims/$SIM_ID.zip test.zip
            mkdir /bender/sim
            unzip test.zip -d /bender/sim
      - run:
          name: pip install new zpy
          command: ${BLENDERPIP} install .
      - run:
          name: fake assets dir
          command: |
            mkdir -p /tmp/lib/hdris/1k
            cp /bender/sim/textures/test_hdri.hdr /tmp/lib/hdris/1k/test_hdri.hdr
            mkdir -p /tmp/lib/textures/random_512p
            cp /bender/sim/textures/test_texture.jpg /tmp/lib/textures/random_512p/test_texture.jpg
      - run:
          name: run test sim
          command: |
            set -eo pipefail

            /bin/blender-softwaregl --background --enable-autoexec --python /bender/launcher.py &
            ${BLENDERPY} /bender/launcher_helper.py --generate --sim_dir /bender/sim

  tag:
    working_directory: ~/repo
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "d7:93:58:7b:31:e3:62:53:2d:72:a4:a0:90:8b:8c:a8"
      - run:
          name: Tag Branch
          command: |
            VERSION=$(git rev-parse --abbrev-ref HEAD | awk '{split($0,a,"-"); print a[2]}')
            git config user.email "infra@zumolabs.ai"
            git config user.name "CircleCI"
            git tag -f $VERSION
            git push origin $VERSION -f

  build:
    working_directory: ~/repo
    docker:
      - image: python:3.6
    steps:
      - checkout
      - run:
          name: build zpy package
          command: python setup.py sdist bdist_wheel
      - run:
          name: build zpy addon
          command: |
            apt-get update && apt-get install -y --no-install-recommends zip
            IMAGE_TAG=$(git describe --tags --dirty --always)
            export ZPY_VERSION=$IMAGE_TAG
            ./package_addon.sh
      - persist_to_workspace:
          root: ~/repo
          paths:
            - dist/*
            - ./*.zip

  publish-pypi:
    working_directory: ~/repo
    docker:
      - image: python:3.6
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: publish package
          command: |
            pip install --upgrade twine
            twine upload dist/*

  publish-github-release:
    working_directory: ~/repo
    docker:
      - image: cibuilds/github:0.10
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - run:
          name: publish Release on github
          command: |
            VERSION=$(git describe --tags --dirty --always)
            cp *.zip dist/
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ~/repo/dist

workflows:
  version: 2
  build-publish:
    jobs:
      - test:
          filters:
            branches:
              only: /release-v.*/
      - tag:
          requires:
            - test
          filters:
            branches:
              only: /release-v.*/
      - build:
          requires:
            - tag
          filters:
            branches:
              only: /release-v.*/
      - publish-pypi:
          requires:
            - build
          filters:
            branches:
              only: /release-v.*/
      - publish-github-release:
          requires:
            - build
          filters:
            branches:
              only: /release-v.*/
